### PR TITLE
Add philosophers spark session

### PR DESCRIPTION
**Pull request by krusts31**
Hey guys! What do you think? I know that there are some cosmetic issues. I want to know what is good and what needs to be improved. Cheers!

### CODE REVIEW

**Comment by joppekoers** [comment]
TODO

bit more verbose, make it more like a story
remove ex0* and give descriptive names
Remove time limits

Deadlock thought process
	- What is it
	- Why is it bad
	- Why you should prevent them
	- How to prevent them
	- Done

**Comment by W2Wizard** [comment]
@krusts31 Are you going to still work on this ?

**Comment by krusts31** [comment]
Yes I am working on it here
https://github.com/krusts31/philosopher-sprak-session

**Comment by W2Wizard** [comment]
Changed it with @krusts31 to do his work now ONLY on the philo branch in this repo instead.

Also just a note I suggest you remove all the italic E's

**Comment by krusts31** [comment]
Yeah, I am still working on my repo, I forgot about the branch we made. I
gave the spark session to someone to correct my grammar and spelling
mistakes. Will update it on the branch ASAP.

pirmd., 2022. g. 23. maijs, plkst. 10:48 — lietotājs W2.Wizard (<
***@***.***>) rakstīja:

**Comment by joppekoers** [comment]
There is a problem: in commit ed151e778eecc5d3831da3a07479280a36630fb3 you renamed the files could you rewrite the history so that rename doesn’t happen and we can see the evaluation of this spark session in a single file?

**Comment by W2Wizard** [comment]
As I'm rewriting these sessions, the current plan of spark-sessions is to go only up to a graphics project.

That means only:
- `libft`
- `ft_printf`
- `get_next_line`

Will get a spark session, however it will also include a MLX42 graphics session to help out with understanding and using the lib.

So, sorry for this but this PR will be closed, also because its pretty much stale.

**Pull request closed without merging**
